/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/mnt/e/workspace/front-end-interview/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-77365a8f",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77365a8f").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-43afc975",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-43afc975").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-3760182e",
    path: "/guide/abstract.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3760182e").then(next)
    },
  },
  {
    name: "v-0c07674c",
    path: "/guide/babel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c07674c").then(next)
    },
  },
  {
    name: "v-288c6bc0",
    path: "/guide/book.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-288c6bc0").then(next)
    },
  },
  {
    name: "v-59ee51ec",
    path: "/guide/algorithm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59ee51ec").then(next)
    },
  },
  {
    name: "v-6fc252cc",
    path: "/guide/browser.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6fc252cc").then(next)
    },
  },
  {
    name: "v-5a77c6b2",
    path: "/guide/carousel.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a77c6b2").then(next)
    },
  },
  {
    name: "v-7f1230ac",
    path: "/guide/component.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f1230ac").then(next)
    },
  },
  {
    name: "v-091fd91c",
    path: "/guide/common.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-091fd91c").then(next)
    },
  },
  {
    name: "v-73f6fc2c",
    path: "/guide/componentCli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73f6fc2c").then(next)
    },
  },
  {
    name: "v-52e9641c",
    path: "/guide/cssBasic.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52e9641c").then(next)
    },
  },
  {
    name: "v-1ed1572c",
    path: "/guide/babelPlugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ed1572c").then(next)
    },
  },
  {
    name: "v-d55571a8",
    path: "/guide/dataStructure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d55571a8").then(next)
    },
  },
  {
    name: "v-5d21cd2c",
    path: "/guide/deepclone.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d21cd2c").then(next)
    },
  },
  {
    name: "v-4b784e20",
    path: "/guide/designPatterns.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b784e20").then(next)
    },
  },
  {
    name: "v-eccdc8e8",
    path: "/guide/devsProxy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eccdc8e8").then(next)
    },
  },
  {
    name: "v-0d5698ec",
    path: "/guide/composite.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d5698ec").then(next)
    },
  },
  {
    name: "v-40595d6c",
    path: "/guide/engineering.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40595d6c").then(next)
    },
  },
  {
    name: "v-6aa4dd4c",
    path: "/guide/event.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6aa4dd4c").then(next)
    },
  },
  {
    name: "v-80975b68",
    path: "/guide/eventLoop.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-80975b68").then(next)
    },
  },
  {
    name: "v-7db1132c",
    path: "/guide/execute.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7db1132c").then(next)
    },
  },
  {
    name: "v-3bf51368",
    path: "/guide/framework.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3bf51368").then(next)
    },
  },
  {
    name: "v-63a81434",
    path: "/guide/hoisting.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63a81434").then(next)
    },
  },
  {
    name: "v-1cda5bc4",
    path: "/guide/hr.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1cda5bc4").then(next)
    },
  },
  {
    name: "v-741db8e8",
    path: "/guide/fiber.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-741db8e8").then(next)
    },
  },
  {
    name: "v-3d97ba6c",
    path: "/guide/htmlBasic.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d97ba6c").then(next)
    },
  },
  {
    name: "v-27963bec",
    path: "/guide/httpWritten.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27963bec").then(next)
    },
  },
  {
    name: "v-bea4403c",
    path: "/guide/http.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bea4403c").then(next)
    },
  },
  {
    name: "v-64283ccc",
    path: "/guide/immutable.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64283ccc").then(next)
    },
  },
  {
    name: "v-382955a8",
    path: "/guide/jsBasic.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-382955a8").then(next)
    },
  },
  {
    name: "v-7c72c04c",
    path: "/guide/jsWritten.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c72c04c").then(next)
    },
  },
  {
    name: "v-b3faadb4",
    path: "/guide/load.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b3faadb4").then(next)
    },
  },
  {
    name: "v-1d75762c",
    path: "/guide/mechanism.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d75762c").then(next)
    },
  },
  {
    name: "v-ec9af29c",
    path: "/guide/WebpackHMR.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ec9af29c").then(next)
    },
  },
  {
    name: "v-efd21068",
    path: "/guide/preface.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-efd21068").then(next)
    },
  },
  {
    name: "v-10c2faee",
    path: "/guide/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-10c2faee").then(next)
    },
  },
  {
    name: "v-288c14cc",
    path: "/guide/reactHook.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-288c14cc").then(next)
    },
  },
  {
    name: "v-1e3effec",
    path: "/guide/react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e3effec").then(next)
    },
  },
  {
    name: "v-6351ecae",
    path: "/guide/reactivity.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6351ecae").then(next)
    },
  },
  {
    name: "v-6856c158",
    path: "/guide/setState.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6856c158").then(next)
    },
  },
  {
    name: "v-71c96040",
    path: "/guide/router.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71c96040").then(next)
    },
  },
  {
    name: "v-cd21cb20",
    path: "/guide/memory.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cd21cb20").then(next)
    },
  },
  {
    name: "v-c97456e8",
    path: "/guide/redux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c97456e8").then(next)
    },
  },
  {
    name: "v-6d34c850",
    path: "/guide/string.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d34c850").then(next)
    },
  },
  {
    name: "v-1cc3aaf2",
    path: "/guide/security.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1cc3aaf2").then(next)
    },
  },
  {
    name: "v-1c86928c",
    path: "/guide/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c86928c").then(next)
    },
  },
  {
    name: "v-18f12b84",
    path: "/guide/virtualDom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18f12b84").then(next)
    },
  },
  {
    name: "v-1b1892ac",
    path: "/guide/tcp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b1892ac").then(next)
    },
  },
  {
    name: "v-27a016ec",
    path: "/guide/webpackMoudle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27a016ec").then(next)
    },
  },
  {
    name: "v-6a7e1318",
    path: "/guide/resume.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a7e1318").then(next)
    },
  },
  {
    name: "v-56917de8",
    path: "/guide/webpackLoader.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56917de8").then(next)
    },
  },
  {
    name: "v-30a8042c",
    path: "/guide/webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30a8042c").then(next)
    },
  },
  {
    name: "v-bfcc75e8",
    path: "/guide/webpackPlugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bfcc75e8").then(next)
    },
  },
  {
    name: "v-0e9d958c",
    path: "/guide/webpackPluginDesign.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e9d958c").then(next)
    },
  },
  {
    name: "v-888cdde8",
    path: "/guide/dom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-888cdde8").then(next)
    },
  },
  {
    name: "v-6944b2a8",
    path: "/guide/project.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6944b2a8").then(next)
    },
  },
  {
    name: "v-7c06090c",
    path: "/guide/ast.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c06090c").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]